---
- name: backup platform
  hosts: all
  roles:
  - volttron.deployment.set_defaults
  vars:
  - output_archive_name: /tmp/volttron_deployment_backup.tar.gz
  - retrieve_archive: False
  - retrieved_archive_dest_prefix: "archives/"

  tasks:
  - name: create archive of volttron home and root
    archive:
      path:
      - "{{ volttron_home }}"
      - "{{ volttron_root }}"
      dest: "{{ output_archive_name }}"
      format: gz
  - name: retrieve archive
    when: retrieve_archive | bool
    fetch:
      src: "{{ output_archive_name }}"
      dest: "{{ retrieved_archive_dest_prefix }}/{{ inventory_hostname }}/"
      flat: yes
